#!/usr/bin/python3
""" Display X-Request-Id
Usage: ./1-hbtn_header.py <URL>
"""
from urllib import request
import sys


def new_request():
    """Representation request header function"""
    value = {"email": sys.argv[2]}
    data = urllib.parse.urlencode(value).encode("ascii")
    reqt = request.Request(sys.argv[1], data)
    with request.urlopen(reqt) as response:
        print(response.read().decode("utf-8")


if __name__ == "__main__":
    new_request()
